server:
  port: 1200
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost/digital_banking_db"
    username: "root"
    password: "manojkumar"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: digitalbanking.mcaproject@gmail.com
    password: hkrkjsbznxfsscli
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
upload:
  file:
    name: "profile-pictures/"

